Repository yocra3/epimutacions, pull requests merged in 2020-11, with the labels that each got.

#34 Task1
  DESCRIPTION
  NAMESPACE
  R/BumpBetaMatrix.R
  R/EpiMutations.R
  tests/testthat.R
Labels: implementation

#47 Task15
  R/genomicratioset.R
  data/genomicratioset.rda
  man/genomicratioset.Rd
Labels: documentation, enhancement

#45 improve EpiMutations() output
  R/EpiMutations.R
  man/EpiMutations.Rd
  man/format_bumps.Rd
  man/run_bumphunter.Rd
Labels: enhancement, implementation

#46 epimutations() sample_ids argument now runs on a set of samples
  R/EpiMutations.R
  man/EpiMutations.Rd
Labels: enhancement

#48 Task2b
  R/epi_detection_barbosa.R
Labels: implementation

#60 all 20 CpG are now within 1000 bp sequence
  R/genomicratioset.R
  data/genomicratioset.rda
  man/genomicratioset.Rd
Labels: documentation

#62 Task3b - Added OMIM annotation and added comments to function
  R/annotateDMR.R
Labels: annotation
